export enum AppRoute {
  LOGIN = "login",
  ORGANIZATIONS = "organizations",
  DIMENSIONS = "dimensions",
  STRATEGIES = "strategies",
  ENTITIES = "entities",
  "RESOURCES-MANAGEMENT" = "resources-management",
  "RESOURCES-UNUTILIZED" = "resources-unutilized",
  "RISK-SCORING-MODEL" = "risk-scoring-model",
  "MITIGATION" = "mitigation",
  "CONTROL-PARAMETERS" = "control-parameters",
  "KEY-PROCESS" = "key-process",
  "MITIGATION-MANAGEMENT" = "mitigation-management",
  "CONTROL-MANAGEMENT" = "control-management",
  "HEATMAP" = "heatmap",
  "RISK-HEATMAP" = "risk-heatmap",
  "RISK-MANAGEMENT" = "risk-management",
  "RISK-ASSESSMENTS" = "risk-assessments",
  "RISK-ROOT-CAUSES" = "risk-root-causes",
  "Audit" = "audit",
  "RISK-FEEDBACK" = "risk-feedback",
  "RESOURCES-SKILLS" = "resources-skills",
  "RESOURCES-FUNCTIONS" = "resources-functions",
  "RESOURCES-PERFORMANCE-RATING" = "resources-performance-rating",
  "CONTROL-DESIGN-RATING" = "control-design-rating",
  "AUDIT-PLAN" = "audit-plan",
  "CONTROL-EFFECTIVENESS" = "control-effectiveness",
  "CONTROL-EFFECTIVENESS-ASSESSMENT" = "control-effectiveness-assessment",
  "AUDIT-PLAN-FEEDBACK" = "audit-plan-feedback",
  "AUDIT-PLAN-SCHEDULE" = "audit-plan-schedule",
  "AUDIT-PLAN-MEMORANDUM" = "audit-plan-memorandum",
  "EVEDENCE-MANAGEMENT_LEVEL" = "evLevel",
  "TESTING-NATURE-MANAGEMENT" = "testing-nature",
  "Storage-Location" = "storage-location",
}

export const appRoutes = {
  LOGIN: `${AppRoute.LOGIN}`,
  ORGANIZATIONS: `${AppRoute.ORGANIZATIONS}`,
  DIMENSIONS: `${AppRoute.DIMENSIONS}`,
  STRATEGIES: `${AppRoute.STRATEGIES}`,
  ENTITIES: `${AppRoute.ENTITIES}`,
  "RESOURCES-MANAGEMENT": `${AppRoute["RESOURCES-MANAGEMENT"]}`,
  "RESOURCES-UNUTILIZED": `${AppRoute["RESOURCES-UNUTILIZED"]}`,
  "RISK-SCORING-MODEL": `${AppRoute["RISK-SCORING-MODEL"]}`,
  MITIGATION: `${AppRoute.MITIGATION}`,
  "CONTROL-PARAMETERS": `${AppRoute["CONTROL-PARAMETERS"]}`,
  HEATMAP: `${AppRoute.HEATMAP}`,
  "RISK-HEATMAP": `${AppRoute["RISK-HEATMAP"]}`,
  "KEY-PROCESS": `${AppRoute["KEY-PROCESS"]}`,
  "MITIGATION-MANAGEMENT": `${AppRoute["MITIGATION-MANAGEMENT"]}`,
  "CONTROL-MANAGEMENT": `${AppRoute["CONTROL-MANAGEMENT"]}`,
  "RISK-MANAGEMENT": `${AppRoute["RISK-MANAGEMENT"]}`,
  "RISK-ASSESSMENTS": `${AppRoute["RISK-ASSESSMENTS"]}`,
  "RISK-ROOT-CAUSES": `${AppRoute["RISK-ROOT-CAUSES"]}`,
  Audit: `${AppRoute.Audit}`,
  "RISK-FEEDBACK": `${AppRoute["RISK-FEEDBACK"]}`,
  "RESOURCES-SKILLS": `${AppRoute["RESOURCES-SKILLS"]}`,
  "RESOURCES-FUNCTIONS": `${AppRoute["RESOURCES-FUNCTIONS"]}`,
  "RESOURCES-PERFORMANCE-RATING": `${AppRoute["RESOURCES-PERFORMANCE-RATING"]}`,
  "CONTROL-DESIGN-RATING": `${AppRoute["CONTROL-DESIGN-RATING"]}`,
  "AUDIT-PLAN": `${AppRoute["AUDIT-PLAN"]}`,
  "CONTROL-EFFECTIVENESS": `${AppRoute["CONTROL-EFFECTIVENESS"]}`,
  "CONTROL-EFFECTIVENESS-ASSESSMENT": `${AppRoute["CONTROL-EFFECTIVENESS-ASSESSMENT"]}`,
  "AUDIT-PLAN-FEEDBACK": `${AppRoute["AUDIT-PLAN-FEEDBACK"]}`,
  "AUDIT-PLAN-SCHEDULE": `${AppRoute["AUDIT-PLAN-SCHEDULE"]}`,
  "AUDIT-PLAN-MEMORANDUM": `${AppRoute["AUDIT-PLAN-MEMORANDUM"]}`,
  "EVEDENCE-MANAGEMENT_LEVEL": `${AppRoute["EVEDENCE-MANAGEMENT_LEVEL"]}`,
  "TESTING-NATURE-MANAGEMENT": `${AppRoute["TESTING-NATURE-MANAGEMENT"]}`,
  "Storage-Location": `${AppRoute["Storage-Location"]}`,
};

Object.freeze(appRoutes);
